branch: main
version_variable: VERSION
major_on_zero: false
tag_format: v{version}
commit_parser:
  major_pattern: "^(feat|fix|refactor|perf|build|ci|chore|docs|style|test)(\\([\\w\\s-]+\\))?!:"
  minor_pattern: "^feat(\\([\\w\\s-]+\\))?:"
  patch_pattern: "^(fix|refactor|perf|build|ci|chore|docs|style|test)(\\([\\w\\s-]+\\))?:"
changelog:
  template_dir: .github/semantic-release-templates
  changelog_file: CHANGELOG.md
  exclude_commit_patterns:
    - "^chore\\(release\\):"
    