repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
      - id: test
        name: test
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]